name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test Laba3.TestProject
    - name: Publish
      run: dotnet publish laba3 -c Release -r win-x64
