name: Laba3

on: 
  push:
    branches:
      - main

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Test
        run: dotnet test TrpoLab3.Tests

  publish_win:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Publish
        run: dotnet publish TrpoLab3 -c Release -r win-x64 -o $GITHUB_WORKSPACE/$GITHUB_RUN_ID/Laba3.win-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Laba3.win-x64
          path: $GITHUB_WORKSPACE/$GITHUB_RUN_ID/Laba3.win-x64
